# Site
name: 'Gineesh Madapparambath'
title: "i am gini"
description: 'Author of Kubernetes and Ansible books, Automation and Containerization Explorer, techbeatly.com/youtube'
logo: 'assets/images/logo-g-v1.png'
favicon: 'assets/images/logo-g-v1.png'
footer_name: "Gineesh"
keywords: "Personal Notes, Guides, Blogs"
#url: "https://www.iamgini.com/"
my_base_site: "https://www.iamgini.com"
baseurl: ''
# If you are building a GitHub project page then use these settings:
# url: "https://www.iamgini.com/site2/"
# baseurl: "/site2"

disqus: 'iamgini-com'
email: 'net.gini@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

google_analytics: 'UA-158250524-1'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

authors:
  gini:
    name: Gineesh
    display_name: Gineesh Madapparambath
    site: https://www.iamgini.com
    avatar: 'assets/images/avatar.png'
    gravatar: 1558aaf0c06196e6b9cb24c21e5ca858
    email: gini@techbeatly.com
    bio: "Author, Automation and Containerization Guy, techbeatly.com/youtube"
    web: https://www.iamgini.com
    twitter: https://twitter.com/iamgineesh
    description: "Backpacker, Foodie, Techie"

social:
  # - title: twitter
  #   url: https://twitter.com/GiniGangadharan
  #   icon: "fab fa-twitter"
  #- url: https://facebook.com
  #  icon: "fab fa-facebook-f"

  - title: linkedin
    url: https://www.linkedin.com/in/gineesh/
    icon: "fab fa-linkedin-in"
  - title: github
    url: https://github.com/iamgini/
    icon: "fab fa-github"
  - title: instagram
    url: https://www.instagram.com/iamgineesh/
    icon: "fab fa-instagram"
  - title: twitter
    url: https://x.com/iamgineesh
  - title: youtube
    url: https://www.youtube.com/techbeatly

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: gini
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page


# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
# exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
exclude:
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
  - .jekyll-cache

jekyll_admin:
  homepage: "posts"
  hidden_links:
    #- posts
    #- pages
    #- staticfiles
    - datafiles
    #- configuration


# collections:
#   books:
#     output: true
#     permalink: /books/:name/
#     source: _pages/books
